const STORAGE_KEY = "recipes";

function initStorage() {
  let data = localStorage.getItem(STORAGE_KEY);
  if (!data) {
    const defaultRecipe = [
      {
        id: Date.now(),
        title: "Drumstick (Moringa) Curry",
        description:
          "A delicious and mildly spicy drumsticks curry blended with traditional Indian spices for 2 people.",
        ingredients: [
          [
            "2 fresh green drumsticks",
            "1 medium-sized onion",
            "1 medium-sized tomato",
            "1 medium-sized potato",
            "4 garlic cloves",
            "1-inch piece of ginger (approx. 10 grams)",
            "1 fresh green chili",
            "8-10 fresh coriander leaves",
          ],
          [
            "1/2 tsp red chili powder",
            "1/2 tsp turmeric powder",
            "1 and 1/2 tbsp salt",
            "1 tsp curry masala powder",
          ],
          [
            "1 whole red chili",
            "1 green cardamom (elaichi)",
            "1 bay leaf",
            "1/2 tsp cumin seeds",
            "1/2 tsp mustard seeds",
            "2 cloves",
          ],
          ["25 ml sunflower oil and 500 ml drinkable water"],
          [
            "Gas stove & lighter (fully functional)",
            "1 large spoon",
            "1 deep cooking pan",
            "1 cup (approx. 60 ml)",
            "3-4 small bowls",
            "1 cotton kitchen towel (to handle hot pan)",
            "1 chopping board and 1 kitchen knife (used for cutting vegetables)",
            "1 flat plate (steel/aluminum)",
            "1 plate and 1 spoon (for serving)",
            "1 peeler (for peeling vegetables)",
          ],
        ],
        steps: [
          ["Place the chopping board on a clean, flat surface."],
          ["Place a small bowl for drumsticks next to the chopping board."],
          ["Wash the two drumsticks under running tap water for 10 seconds."],
          [
            "Cut the drumsticks into 2-inch pieces using the knife and chopping board.",
          ],
          ["Place the cut drumsticks into the drumstick bowl."],
          ["Place a small bowl for potato next to the chopping board."],
          ["Peel the potato with the peeler."],
          ["Cut the potato into small cubes using the knife."],
          [
            "Rinse the cut potato cubes with running water and place in the potato bowl.",
          ],
          ["Place a small bowl for tomato next to the chopping board."],
          ["Wash the tomato under running water."],
          [
            "Cut the tomato into small pieces using the knife and place in the tomato bowl.",
          ],
          ["Place a small bowl for onion next to the chopping board."],
          ["Peel the onion."],
          ["Wash the peeled onion under running water."],
          [
            "Cut the onion into small pieces using the knife and place in the onion bowl.",
          ],
          [
            "Place a small bowl for garlic and ginger next to the chopping board.",
          ],
          ["Peel the garlic cloves."],
          [
            "Chop the garlic cloves into very small pieces using the knife and place in the garlic bowl.",
          ],
          ["Peel the ginger piece using the peeler."],
          ["Wash the peeled ginger under running water."],
          [
            "Chop the ginger into tiny pieces using the knife and place in the garlic bowl with garlic.",
          ],
          ["Place a small bowl for green chili next to the chopping board."],
          ["Cut the green chili vertically into two halves."],
          [
            "Place the cut green chili into the garlic bowl with garlic and ginger.",
          ],
          ["Place the deep cooking pan on the gas stove."],
          ["Turn on the gas stove and ignite the flame with a lighter."],
          ["Set the flame to medium."],
          ["Add 25 ml sunflower oil into the pan."],
          ["Wait 20-30 seconds for the oil to heat."],
          [
            "Add all whole spices (1 whole red chili, 1 green cardamom, 1 bay leaf, 1/2 tsp cumin seeds, 1/2 tsp mustard seeds, 2 cloves) into the hot oil.",
          ],
          [
            "Stir the whole spices with a large spoon for 30-40 seconds until they crackle.",
          ],
          ["Add chopped onion pieces into the pan."],
          [
            "Stir the onion continuously with a large spoon on medium flame for 4-5 minutes until golden brown.",
          ],
          [
            "Add chopped garlic and ginger pieces from the garlic bowl into the pan.",
          ],
          [
            "Stir continuously with a large spoon for 2-3 minutes along with the onion.",
          ],
          ["Add chopped tomato pieces from the tomato bowl into the pan."],
          [
            "Mix well with a large spoon and cook for 2-3 minutes until tomatoes become soft and mushy.",
          ],
          ["Add cut potato pieces from the potato bowl into the pan."],
          ["Stir with a large spoon and cook on medium flame for 2 minutes."],
          [
            "Add powdered spices (1/2 tsp red chili powder, 1/2 tsp turmeric powder, 1 and 1/2 tbsp salt, 1 tsp curry masala powder) into the pan.",
          ],
          [
            "Mix well with a spoon and cook for 2 minutes until oil separates from the masala.",
          ],
          ["Add cut drumstick pieces from the drumstick bowl into the pan."],
          [
            "Mix well with the masala and cook for 2-3 minutes on medium flame.",
          ],
          ["Add 500 ml drinkable water into the pan."],
          ["Mix everything well with a spoon."],
          ["Increase flame to high and bring the mixture to a boil."],
          ["Once boiling, reduce flame to medium-low."],
          ["Cover the pan with a flat plate as lid."],
          ["Cook for 15-20 minutes until drumsticks and potatoes are soft."],
          ["Use a kitchen towel to open the lid carefully."],
          [
            "Check if drumsticks and potatoes are cooked by piercing with a spoon.",
          ],
          ["If not fully cooked, cover again and cook for another 5 minutes."],
          ["Turn off the stove and wait 1-2 minutes."],
          ["Open the lid carefully using the kitchen towel."],
          ["Transfer the hot curry into a serving plate."],
          ["Garnish with 8-10 fresh coriander leaves."],
          ["Serve hot with boiled rice or rotis."],
        ],
        prep: 40,
        difficulty: "Medium",
        image:
          "https://images.pexels.com/photos/20466259/pexels-photo-20466259.jpeg",
      },
      {
        id: Date.now() + 1,
        title: "Maggi Masala Noodles",
        description:
          "A detailed step-by-step Maggi Masala noodles recipe, portioned for 2 people",
        ingredients: [
          ["1 packet Maggi noodles (Approx. 150 gms)"],
          ["1 small onion"],
          ["1 small tomato"],
          ["1 small carrot"],
          ["1/4 cup green peas (fresh or frozen)"],
          ["1 green chili (optional)"],
          ["1 tsp chopped coriander leaves (for garnish)"],
          ["1 tsp oil"],
          ["1/4 tsp turmeric powder"],
          ["1/4 tsp red chili powder"],
          ["1/4 tsp salt (adjust to taste)"],
          ["1/2 tsp Maggi tastemaker masala (from the packet)"],
          ["1/2 cup water (approx. 125 ml)"],
          ["1 small frying pan or wok"],
          ["1 small spatula or spoon"],
          ["1 small chopping board"],
          ["1 small knife"],
          ["1 small bowl for onions"],
          ["1 small bowl for tomato"],
          ["1 small bowl for carrot"],
          ["1 small bowl for green peas"],
          ["1 small bowl for chopped green chili"],
          ["1 small bowl for chopped coriander leaves"],
        ],
        steps: [
          ["Place the chopping board on a flat, clean surface."],
          ["Place a small bowl next to the chopping board for the onion."],
          ["Peel the onion using the knife and peeler if necessary."],
          ["Chop the onion into small pieces using the knife."],
          ["Transfer the chopped onion into the onion bowl."],
          ["Wash the tomato under running water for 10 seconds."],
          ["Place the tomato on the chopping board."],
          ["Chop the tomato into small cubes using the knife."],
          ["Transfer the chopped tomato into the tomato bowl."],
          ["Peel the carrot using a peeler."],
          ["Chop the carrot into small cubes using the knife."],
          ["Transfer the chopped carrot into the carrot bowl."],
          ["Wash green peas under running water if fresh."],
          ["Transfer the green peas into the green peas bowl."],
          ["Wash the green chili under running water."],
          ["Chop the green chili into small pieces using the knife."],
          ["Transfer the chopped green chili into its dedicated bowl."],
          ["Wash the coriander leaves under running water."],
          ["Chop the coriander leaves finely using the knife."],
          ["Transfer the chopped coriander leaves into the coriander bowl."],
          ["Place the frying pan on the stove and ensure it is stable."],
          ["Turn on the stove to medium flame."],
          ["Add 1 tsp oil into the pan."],
          ["Wait for 10-15 seconds until the oil slightly heats up."],
          ["Add the chopped onions from the onion bowl into the pan."],
          [
            "Stir the onions continuously with the spatula for 2 minutes until translucent.",
          ],
          [
            "Add the chopped tomato, carrot, green peas, and green chili from their bowls into the pan.",
          ],
          [
            "Stir the vegetables continuously for 2 minutes until slightly soft.",
          ],
          [
            "Add 1/4 tsp turmeric powder, 1/4 tsp red chili powder, and 1/4 tsp salt into the pan.",
          ],
          [
            "Mix the spices thoroughly with the vegetables using the spatula for 30 seconds.",
          ],
          ["Pour 1/2 cup of water from a clean container into the pan."],
          ["Wait for the water to reach a gentle boil."],
          [
            "Break the Maggi noodle cake into 3-4 pieces and place them into the boiling water.",
          ],
          [
            "Stir the noodles gently with the spatula for 1-2 minutes to separate them.",
          ],
          ["Add 1/2 tsp Maggi tastemaker masala from the packet into the pan."],
          [
            "Mix the noodles, vegetables, and masala continuously for 2 minutes until the noodles soften and the water is mostly absorbed.",
          ],
          [
            "Turn off the stove and remove the pan carefully using a kitchen towel if needed.",
          ],
          [
            "Sprinkle the chopped coriander leaves from the bowl on top of the noodles for garnish.",
          ],
          [
            "Use a clean spoon to transfer the cooked Maggi Masala noodles into a plate or bowl.",
          ],
          ["Serve immediately, portioned for 2 people."],
        ],
        prep: 15,
        difficulty: "Easy",
        image:
          "https://images.pexels.com/photos/2347311/pexels-photo-2347311.jpeg",
      },
      {
        id: Date.now() + 2,
        title: "Chicken Curry",
        description:
          "A spicy and flavorful chicken curry prepared with traditional Indian spices, suitable for 2 people.",
        ingredients: [
          [
            "250 grams chicken (cut into small pieces, bone-in or boneless)",
            "1 medium-sized onion",
            "1 medium-sized tomato",
            "2 garlic cloves",
            "1-inch piece of ginger (approx. 10 grams)",
            "1 fresh green chili",
            "8-10 fresh coriander leaves",
            "1/4 cup plain yogurt",
          ],
          [
            "1/2 tsp red chili powder",
            "1/2 tsp turmeric powder",
            "1 tsp coriander powder",
            "1/2 tsp garam masala powder",
            "1 and 1/2 tsp salt",
          ],
          [
            "1 whole red chili",
            "1 green cardamom (elaichi)",
            "1 bay leaf",
            "1/2 tsp cumin seeds",
            "1/2 tsp mustard seeds",
            "2 cloves",
          ],
          ["2 tbsp cooking oil", "1/2 cup drinkable water (approx. 125 ml)"],
          [
            "Gas stove & lighter (fully functional)",
            "1 large spoon",
            "1 deep cooking pan",
            "1 small bowl for onion",
            "1 small bowl for tomato",
            "1 small bowl for garlic and ginger",
            "1 small bowl for green chili",
            "1 small bowl for coriander leaves",
            "1 small bowl for chicken pieces",
            "1 chopping board and 1 kitchen knife",
            "1 flat plate (as lid)",
            "1 plate and 1 spoon (for serving)",
            "1 peeler (for peeling vegetables)",
          ],
        ],
        steps: [
          ["Place the chopping board on a clean, flat surface."],
          ["Place a small bowl for chicken pieces next to the chopping board."],
          ["Wash the chicken pieces under running water for 15 seconds."],
          ["Place the chicken pieces into the chicken bowl."],
          ["Place a small bowl for onion next to the chopping board."],
          ["Peel the onion using the peeler if needed."],
          ["Wash the peeled onion under running water."],
          ["Chop the onion into small pieces using the knife."],
          ["Place chopped onion in the onion bowl."],
          ["Place a small bowl for tomato next to the chopping board."],
          ["Wash the tomato under running water."],
          ["Cut the tomato into small pieces using the knife."],
          ["Place chopped tomato in the tomato bowl."],
          [
            "Place a small bowl for garlic and ginger next to the chopping board.",
          ],
          ["Peel the garlic cloves."],
          [
            "Chop garlic cloves into small pieces using the knife and place in garlic bowl.",
          ],
          ["Peel the ginger piece using the peeler."],
          ["Wash the peeled ginger under running water."],
          [
            "Chop the ginger into small pieces and place in garlic bowl with garlic.",
          ],
          ["Place a small bowl for green chili next to the chopping board."],
          ["Cut the green chili vertically into two halves."],
          ["Place cut green chili into the green chili bowl."],
          ["Wash the coriander leaves under running water."],
          ["Chop coriander leaves finely and place in coriander bowl."],
          ["Place deep cooking pan on the gas stove."],
          ["Turn on the gas stove and ignite the flame using a lighter."],
          ["Set the flame to medium."],
          ["Add 2 tbsp cooking oil into the pan."],
          ["Wait 20-30 seconds for the oil to heat."],
          [
            "Add all whole spices (1 whole red chili, 1 green cardamom, 1 bay leaf, 1/2 tsp cumin seeds, 1/2 tsp mustard seeds, 2 cloves) into the hot oil.",
          ],
          [
            "Stir the whole spices with a large spoon for 30-40 seconds until they crackle.",
          ],
          ["Add chopped onion pieces from the onion bowl into the pan."],
          [
            "Stir continuously on medium flame for 4-5 minutes until golden brown.",
          ],
          ["Add chopped garlic and ginger pieces into the pan."],
          ["Stir for 2-3 minutes continuously with onion."],
          ["Add chopped tomato pieces from tomato bowl into the pan."],
          [
            "Mix well and cook for 2-3 minutes until tomatoes become soft and mushy.",
          ],
          [
            "Add red chili powder, turmeric powder, coriander powder, and salt into the pan.",
          ],
          [
            "Mix well and cook for 1-2 minutes until oil separates from the masala.",
          ],
          ["Add chicken pieces from chicken bowl into the pan."],
          ["Mix thoroughly with the masala for 2-3 minutes on medium flame."],
          ["Add 1/4 cup yogurt into the pan."],
          ["Mix the yogurt evenly with the chicken and masala for 1 minute."],
          ["Add 1/2 cup drinkable water into the pan."],
          ["Mix everything well with a large spoon."],
          ["Increase flame to high and bring mixture to a gentle boil."],
          ["Once boiling, reduce flame to medium-low."],
          ["Cover the pan with a flat plate as lid."],
          ["Cook for 20-25 minutes until chicken is fully cooked."],
          ["Use a kitchen towel to carefully remove the lid."],
          [
            "Check doneness by piercing chicken with a spoon; if not cooked, cover and cook for another 5 minutes.",
          ],
          ["Turn off the stove and wait 1-2 minutes."],
          ["Open the lid carefully using a kitchen towel."],
          ["Transfer hot chicken curry into a serving plate."],
          ["Garnish with chopped coriander leaves."],
          ["Serve hot with rice or rotis."],
        ],
        prep: 60,
        difficulty: "Hard",
        image:
          "https://images.pexels.com/photos/31692606/pexels-photo-31692606.jpeg",
      },
    ];
    localStorage.setItem(STORAGE_KEY, JSON.stringify(defaultRecipe));
  }
}

initStorage();
